import { Platform, StatusBar, StyleSheet } from 'react-native';
import { theme } from './theme';

const { colors, elevation, rounded, spacing, typography } = theme;
const topSafePadding = Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) + spacing.md : spacing.md;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topAppBar: {
    minHeight: 72,
    paddingHorizontal: spacing.marginMobile,
    paddingTop: topSafePadding,
    paddingBottom: spacing.md,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  appBarIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: rounded.full,
    borderColor: colors.primaryFixed,
    borderWidth: 2,
    backgroundColor: colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: colors.onPrimary,
    fontSize: typography.labelMd.fontSize,
    fontWeight: '700',
  },
  appBarTitle: {
    color: colors.primary,
    fontSize: typography.headlineLg.fontSize,
    fontWeight: '700',
    lineHeight: typography.headlineLg.lineHeight,
  },
  appBarIconButton: {
    width: 44,
    height: 44,
    borderRadius: rounded.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    paddingHorizontal: spacing.marginMobile,
    paddingTop: spacing.lg,
    paddingBottom: 128,
    gap: spacing.md,
  },
  header: {
    paddingTop: spacing.sm,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: typography.labelMd.fontSize,
    fontWeight: '700',
    lineHeight: typography.labelMd.lineHeight,
    textTransform: 'uppercase',
  },
  title: {
    marginTop: spacing.sm,
    color: colors.onSurface,
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 40,
  },
  subtitle: {
    marginTop: spacing.sm,
    color: colors.onSurfaceVariant,
    fontSize: typography.bodyMd.fontSize,
    lineHeight: typography.bodyMd.lineHeight,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  sensor: {
    flexBasis: '45%',
    flexGrow: 1,
    minHeight: 118,
    borderRadius: rounded.lg,
    backgroundColor: colors.surfaceContainerLowest,
    padding: spacing.md,
    justifyContent: 'space-between',
    ...elevation.card,
  },
  sensorLabel: {
    color: colors.onSurfaceVariant,
    fontSize: typography.labelMd.fontSize,
    fontWeight: typography.labelMd.fontWeight,
    lineHeight: typography.labelMd.lineHeight,
  },
  sensorValue: {
    color: colors.onSurface,
    fontSize: typography.sensorValue.fontSize,
    fontWeight: typography.sensorValue.fontWeight,
    lineHeight: typography.sensorValue.lineHeight,
  },
  panel: {
    borderRadius: rounded.lg,
    backgroundColor: colors.surfaceContainerLowest,
    padding: spacing.md,
    gap: spacing.md,
    ...elevation.card,
  },
  panelTitle: {
    color: colors.onSurface,
    fontSize: typography.headlineMd.fontSize,
    fontWeight: typography.headlineMd.fontWeight,
    lineHeight: typography.headlineMd.lineHeight,
  },
  deviceRow: {
    minHeight: 64,
    borderTopColor: colors.surfaceContainerHigh,
    borderTopWidth: 1,
    paddingTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  deviceName: {
    color: colors.onSurface,
    fontSize: typography.bodyLg.fontSize,
    fontWeight: '600',
    lineHeight: typography.bodyLg.lineHeight,
  },
  deviceState: {
    marginTop: spacing.xs,
    color: colors.onSurfaceVariant,
    fontSize: typography.labelMd.fontSize,
  },
  segmentedControl: {
    minHeight: 40,
    borderRadius: rounded.full,
    backgroundColor: colors.surfaceContainerHigh,
    padding: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  segmentedItem: {
    minWidth: 52,
    height: 34,
    borderRadius: rounded.full,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  segmentedItemActive: {
    backgroundColor: colors.primary,
  },
  segmentedText: {
    color: colors.onSurfaceVariant,
    fontSize: typography.labelMd.fontSize,
    fontWeight: '700',
  },
  iconButton: {
    minWidth: 74,
    height: 44,
    borderRadius: rounded.full,
    backgroundColor: colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonText: {
    color: colors.onPrimary,
    fontWeight: '700',
  },
  primaryButton: {
    height: 52,
    borderRadius: rounded.xl,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...elevation.floating,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontWeight: '700',
    fontSize: typography.bodyMd.fontSize,
  },
  hint: {
    color: colors.onSurfaceVariant,
    fontSize: typography.bodyMd.fontSize,
    lineHeight: typography.bodyMd.lineHeight,
  },
  bottomNavBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 88,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.sm,
    borderTopLeftRadius: rounded.xl,
    borderTopRightRadius: rounded.xl,
    backgroundColor: colors.navGlass,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 10,
  },
  navItem: {
    minWidth: 72,
    minHeight: 56,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: rounded.lg,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  navItemActive: {
    backgroundColor: colors.primaryContainer,
  },
  navLabel: {
    color: colors.onSurfaceVariant,
    fontSize: typography.labelMd.fontSize,
    fontWeight: typography.labelMd.fontWeight,
    lineHeight: typography.labelMd.lineHeight,
  },
  navLabelActive: {
    color: colors.onPrimaryContainer,
  },
  navBadge: {
    position: 'absolute',
    top: -1,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: rounded.full,
    backgroundColor: colors.error,
  },
  loginScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loginKeyboardView: {
    flex: 1,
  },
  loginScrollContent: {
    flexGrow: 1,
  },
  loginTopBar: {
    paddingHorizontal: spacing.marginMobile,
    paddingTop: topSafePadding,
    paddingBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  loginBrandMark: {
    width: 40,
    height: 40,
    borderRadius: rounded.full,
    backgroundColor: colors.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginBrandText: {
    color: colors.primary,
    fontSize: typography.headlineLg.fontSize,
    fontWeight: '700',
    lineHeight: typography.headlineLg.lineHeight,
  },
  loginContent: {
    flex: 1,
    paddingHorizontal: spacing.marginMobile,
    paddingBottom: spacing.xl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: rounded.xl,
    borderColor: colors.outlineVariant,
    borderWidth: 1,
    backgroundColor: colors.surfaceContainerLowest,
    padding: spacing.lg,
    gap: spacing.lg,
    ...elevation.card,
  },
  loginHeader: {
    alignItems: 'center',
    gap: spacing.xs,
  },
  loginTitle: {
    color: colors.onSurface,
    fontSize: typography.headlineMd.fontSize,
    fontWeight: typography.headlineMd.fontWeight,
    lineHeight: typography.headlineMd.lineHeight,
  },
  loginSubtitle: {
    color: colors.onSurfaceVariant,
    fontSize: typography.bodyMd.fontSize,
    lineHeight: typography.bodyMd.lineHeight,
    textAlign: 'center',
  },
  loginForm: {
    gap: spacing.md,
  },
  loginField: {
    minHeight: 52,
    borderRadius: rounded.xl,
    backgroundColor: colors.surfaceContainerLow,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  loginInput: {
    flex: 1,
    color: colors.onSurface,
    fontSize: typography.bodyMd.fontSize,
    lineHeight: typography.bodyMd.lineHeight,
  },
  loginErrorText: {
    color: colors.error,
    fontSize: typography.labelMd.fontSize,
    fontWeight: typography.labelMd.fontWeight,
    lineHeight: typography.labelMd.lineHeight,
    textAlign: 'center',
  },
  loginButton: {
    minHeight: 54,
    borderRadius: rounded.xl,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    ...elevation.floating,
  },
  loginButtonText: {
    color: colors.onPrimary,
    fontSize: typography.bodyLg.fontSize,
    fontWeight: '700',
    lineHeight: typography.bodyLg.lineHeight,
  },
  loginSecureNote: {
    borderTopColor: colors.outlineVariant,
    borderTopWidth: 1,
    paddingTop: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  loginSecureText: {
    color: colors.onSurfaceVariant,
    fontSize: typography.labelMd.fontSize,
    fontWeight: typography.labelMd.fontWeight,
    lineHeight: typography.labelMd.lineHeight,
  },
  skeletonPage: {
    minHeight: 480,
    borderRadius: rounded.lg,
    backgroundColor: colors.surfaceContainerLowest,
    padding: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    ...elevation.card,
  },
  skeletonTitle: {
    color: colors.onSurface,
    fontSize: typography.headlineMd.fontSize,
    fontWeight: typography.headlineMd.fontWeight,
    lineHeight: typography.headlineMd.lineHeight,
    textAlign: 'center',
  },
});
