export const theme = {
  name: 'Smart Living Interface',
  colors: {
    surface: '#f8f9ff',
    surfaceDim: '#cbdbf5',
    surfaceBright: '#f8f9ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eff4ff',
    surfaceContainer: '#e5eeff',
    surfaceContainerHigh: '#dce9ff',
    surfaceContainerHighest: '#d3e4fe',
    onSurface: '#0b1c30',
    onSurfaceVariant: '#464555',
    inverseSurface: '#213145',
    inverseOnSurface: '#eaf1ff',
    outline: '#777587',
    outlineVariant: '#c7c4d8',
    surfaceTint: '#4d44e3',
    primary: '#3525cd',
    onPrimary: '#ffffff',
    primaryContainer: '#4f46e5',
    onPrimaryContainer: '#dad7ff',
    inversePrimary: '#c3c0ff',
    secondary: '#006e2f',
    onSecondary: '#ffffff',
    secondaryContainer: '#6bff8f',
    onSecondaryContainer: '#007432',
    tertiary: '#684000',
    onTertiary: '#ffffff',
    tertiaryContainer: '#885500',
    onTertiaryContainer: '#ffd4a4',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#e2dfff',
    primaryFixedDim: '#c3c0ff',
    onPrimaryFixed: '#0f0069',
    onPrimaryFixedVariant: '#3323cc',
    secondaryFixed: '#6bff8f',
    secondaryFixedDim: '#4ae176',
    onSecondaryFixed: '#002109',
    onSecondaryFixedVariant: '#005321',
    tertiaryFixed: '#ffddb8',
    tertiaryFixedDim: '#ffb95f',
    onTertiaryFixed: '#2a1700',
    onTertiaryFixedVariant: '#653e00',
    background: '#f8f9ff',
    onBackground: '#0b1c30',
    surfaceVariant: '#d3e4fe',
    active: '#22c55e',
    activeTint: '#ecfdf3',
    warning: '#ffb95f',
    navGlass: 'rgba(255, 255, 255, 0.85)',
    selection: '#c3c0ff',
  },
  typography: {
    fontFamily: 'Inter',
    displayLg: {
      fontSize: 48,
      fontWeight: '700',
      lineHeight: 56,
      letterSpacing: 0,
    },
    headlineLg: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: 0,
    },
    headlineMd: {
      fontSize: 20,
      fontWeight: '600',
      lineHeight: 28,
      letterSpacing: 0,
    },
    bodyLg: {
      fontSize: 17,
      fontWeight: '400',
      lineHeight: 24,
      letterSpacing: 0,
    },
    bodyMd: {
      fontSize: 15,
      fontWeight: '400',
      lineHeight: 22,
      letterSpacing: 0,
    },
    labelMd: {
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 18,
      letterSpacing: 0,
    },
    sensorValue: {
      fontSize: 32,
      fontWeight: '600',
      lineHeight: 40,
      letterSpacing: 0,
    },
  },
  rounded: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    unit: 4,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    gutter: 16,
    marginMobile: 20,
  },
  elevation: {
    card: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 2,
    },
    floating: {
      shadowColor: '#3525cd',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 5,
    },
  },
} as const;

export type AppTheme = typeof theme;
